project:
  type: website
  output-dir: docs

website:
  title: "Jueun Kang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Jueun K Resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



